import { beforeEach, describe, test } from "vitest";
import { expect } from "chai";
import { Board } from "../src/Board.mjs";

const CUSTOM_T_BLOCK = [
  `.T.
   TTT
   ...`,
  `.T.
   .TT
   .T.`,
  `...
   TTT
   .T.`,
  `.T.
   TT.
   .T.`,
];

const CUSTOM_I_BLOCK = [
  `.....
   .....
   IIII.
   .....
   .....`,
  `..I..
   ..I..
   ..I..
   ..I..
   .....`,
  `.....
   .....
   IIII.
   .....
   .....`,
  `..I..
   ..I..
   ..I..
   ..I..
   .....`,
];

describe("A falling Tetromino can be rotated", () => {
  let board;
  beforeEach(() => {
    board = new Board(10, 6);
  });

  test("left in the air", () => {
    board.seed(undefined, CUSTOM_T_BLOCK, 1, 1);
    board.rotateLeft();
    expect(board.toString()).to.equalShape(
      `..........
       ..T.......
       .TT.......
       ..T.......
       ..........
       ..........`
    );
  });
  test("right in the air", () => {
    board.seed(undefined, CUSTOM_T_BLOCK, 1, 1);
    board.rotateRight();
    expect(board.toString()).to.equalShape(
      `..........
       ..T.......
       ..TT......
       ..T.......
       ..........
       ..........`
    );
  });
  test("left while touching a wall", () => {
    board.seed(undefined, CUSTOM_T_BLOCK, 0, 1);
    board.rotateLeft();
    expect(board.toString()).to.equalShape(
      `..........
       .T........
       TT........
       .T........
       ..........
       ..........`
    );
  });
  test("right while touching a wall", () => {
    board.seed(undefined, CUSTOM_T_BLOCK, 0, 1);
    board.rotateRight();
    expect(board.toString()).to.equalShape(
      `..........
       .T........
       .TT.......
       .T........
       ..........
       ..........`
    );
  });
  test("while touching the ground", () => {
    board.seed(undefined, CUSTOM_T_BLOCK, 1, 3, 1);
    board.rotateLeft();
    expect(board.toString()).to.equalShape(
      `..........
       ..........
       ..........
       ..T.......
       .TTT......
       ..........`
    );
  });
  test("left while touching another block", () => {
    board.seed(
      `..........
       ..........
       ..........
       ..........
       ....OO....
       ....OO....`,
      CUSTOM_T_BLOCK,
      5,
      2
    );
    board.rotateLeft();
    expect(board.toString()).to.equalShape(
      `..........
       ..........
       ......T...
       .....TT...
       ....OOT...
       ....OO....`
    );
  });
  test("right while touching another block", () => {
    board.seed(
      `..........
       ..........
       ..........
       ..........
       ....OO....
       ....OO....`,
      CUSTOM_T_BLOCK,
      2,
      2
    );

    board.rotateRight();
    expect(board.toString()).to.equalShape(
      `..........
       ..........
       ...T......
       ...TT.....
       ...TOO....
       ....OO....`
    );
  });
});

describe("A falling Tetromino cannot be rotated", () => {
  let board;
  beforeEach(() => {
    board = new Board(10, 6);
  });

  test("left when other blocks are in the way", () => {
    board.seed(
      `..........
       ..........
       ..........
       ..........
       ....OO....
       ....OO....`,
      CUSTOM_T_BLOCK,
      3,
      2
    );

    board.rotateLeft();
    expect(board.toString()).to.equalShape(
      `..........
       ..........
       ....T.....
       ...TTT....
       ....OO....
       ....OO....`
    );
  });
  test("right when other blocks are in the way", () => {
    board.seed(
      `..........
       ..........
       ..........
       ..........
       ....OO....
       ....OO....`,
      CUSTOM_T_BLOCK,
      4,
      2
    );

    board.rotateRight();
    expect(board.toString()).to.equalShape(
      `..........
       ..........
       .....T....
       ....TTT...
       ....OO....
       ....OO....`
    );
  });
  test("when block would reach higher than before (no floor kick)", () => {
    board.seed(undefined, CUSTOM_T_BLOCK, 1, 4);

    board.rotateRight();
    expect(board.toString()).to.equalShape(
      `..........
       ..........
       ..........
       ..........
       ..T.......
       .TTT......`
    );
    board.rotateLeft();
    expect(board.toString()).to.equalShape(
      `..........
       ..........
       ..........
       ..........
       ..T.......
       .TTT......`
    );
  });
});

describe("Wall kick works", () => {
  let board;
  beforeEach(() => {
    board = new Board(8, 6);
  });

  test("on the left side", () => {
    board.seed(undefined, CUSTOM_T_BLOCK, -1, 0, 1);

    board.rotateLeft();
    expect(board.toString()).to.equalShape(
      `.T......
       TTT.....
       ........
       ........
       ........
       ........`
    );
  });
  test("on the right side", () => {
    board.seed(undefined, CUSTOM_T_BLOCK, 6, 0, 3);

    board.rotateRight();
    expect(board.toString()).to.equalShape(
      `......T.
       .....TTT
       ........
       ........
       ........
       ........`
    );
  });
  test("with an I shape on the left", () => {
    board.seed(undefined, CUSTOM_I_BLOCK, -2, 0, 1);

    board.rotateLeft();
    expect(board.toString()).to.equalShape(
      `........
       ........
       IIII....
       ........
       ........
       ........`
    );
  });
  test("with an I shape on the right", () => {
    board.seed(undefined, CUSTOM_I_BLOCK, 5, 0, 1);

    board.rotateRight();
    expect(board.toString()).to.equalShape(
      `........
       ........
       ....IIII
       ........
       ........
       ........`
    );
  });
});

describe("Wall kick does not work on", () => {
  let board;
  beforeEach(() => {
    board = new Board(8, 8);
  });

  test("the left side if it is blocked", () => {
    board.seed(
      `........
       ........
       ........
       ........
       ..I.....
       ..I.....
       ..I.....
       ..I.....`,
      CUSTOM_T_BLOCK,
      -1,
      3,
      1
    );

    board.rotateLeft();
    expect(board.toString()).to.equalShape(
      `........
       ........
       ........
       T.......
       TTI.....
       T.I.....
       ..I.....
       ..I.....`
    );
  });
  test("the right side if it is blocked", () => {
    board.seed(
      `........
       ........
       ........
       ........
       .....I..
       .....I..
       .....I..
       .....I..`,
      CUSTOM_T_BLOCK,
      6,
      3,
      3
    );

    board.rotateLeft();
    expect(board.toString()).to.equalShape(
      `........
       ........
       ........
       .......T
       .....ITT
       .....I.T
       .....I..
       .....I..`
    );
  });
});
